from pico2d import *
import sys
import math
import time
import random
import game_framework




# Min Player state
LEFT_RUN = 0
RIGHT_RUN = 1
LEFT_STAND =2
RIGHT_STAND =3
JUMP_UP=4
JUMP_DOWN=5 
LEFT_SIT=6
RIGHT_SIT =7 
RIGHT_PAUNCH=8
LEFT_PAUNCH=9

# Player State
STATE_STAND =	1
STATE_WALK =	2
STATE_JUMP =	3
STATE_AIR =		4

STATE_PUNCH =	5
STATE_PUNCH2 =	6
STATE_PUNCH3 =	7

STATE_KICK =	6
STATE_SIT =		7
STATE_STAND_GUARD = 8
STATE_SKILL_BURNKNUCKLE  =	9
STATE_SKILL_RISINGTACKLE =	10
STATE_SKILL_POWERGEYSER = 11
STATE_ROLL_DODGE = 12
STATE_HIT = 13
STATE_DIE= 14
STATE_IORI_HIT = 23

# Player Resource State
# animation + 1 ( 1 start)
RES_STAND = 1
RES_WALK = 2
RES_JUMP = 11
RES_SIT = 4
RES_GUARD = 68
RES_PUNCH = 5
RES_KICK = 7
RES_HIT = 8
RES_DIE = 9
RES_BURNKNUCKLE = 10
RES_RISINGTACKLE = 11
RES_POWERGEYSER = 12
RES_POWERGEYSER_EFFECT = 15
RES_ROLL_DODGE = 16
RES_IORI_HIT = 17

# Blanka State
STATE_BLANKA_STAND = 1
STATE_BLANKA_WALK = 2
STATE_BLANKA_KICK = 3
STATE_BLANKA_HIT = 4
STATE_BLANKA_ROLL = 12
STATE_BLANKA_DIE = 6
STATE_BLANKA_BURN_HIT = 7
STATE_BLANKA_PUNCH = 8
STATE_BLANKA_DASH = 9

# Iori
STATE_BOSS_STAND = 1
STATE_BOSS_WALK = 2
STATE_BOSS_PUNCH1 = 13
STATE_BOSS_PUNCH2 = 14
STATE_BOSS_PUNCH3 = 15
STATE_BOSS_SKILL1 = 16
STATE_BOSS_HIT = 6
STATE_BOSS_DIE = 7 
STATE_BOSS_JUMP = 8
STATE_BOSS_DASH = 9
STATE_BOSS_BIT_HIT = 10

# Direction
DIR_RIGHT = 1
DIR_LEFT = -1
DIR_NONE = 0

# Field Collision Check
COLL_BOTTOM = 1
COLL_ONEFLOOR_LEFT = 2
COLL_ONEFLOOR_RIGHT = 3
COLL_TWOFLOOR_CENTER = 4
COLL_THREEFLOOR_LEFT = 5
COLL_THREEFLOOR_RIGHT = 6
COLL_FORTHLOOR_CENTER = 7
COLL_FIVEFLOOR_LEFT = 8
COLL_FIVEFLOOR_RIGHT = 9

# Hit Effect State 
STATE_HIT_EF_MON = 1
STATE_HIT_EF_PLAYER = 2
STATE_HIT_EF_BOSS = 3 

